# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
# Complete reference: https://docs.coderabbit.ai/reference/configuration
language: "en-US"
tone_instructions: "professional and constructive"
early_access: false
enable_free_tier: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_in_walkthrough: false
  review_status: false
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  estimate_code_review_effort: false
  poem: false
  path_filters:
    - "!dist/**"
    - "src/**"
    - "!node_module/**"
    - "!public/**"
    - "!.codacy/**"
    - "!.gemini/**"
    - "!.github/**"
    - "!.kiro/**"
    - "!.idx/**"
    - "!.qodo/**"
    - "!.vscode/**"
    - "!docs/**"
  path_instructions:
    - path: '**/*.{ts,tsx}'
      instructions:
        'Review the Typescript and React code for conformity with best practices in React, and Typescript. Highlight any deviations. Follow .kiro/steering/*.md'
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["master"]
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns: ["**/biome.json", "**/.kiro/steering/*.md"]
